#!/bin/bash

while getopts HDV:P: opt; do
    case $opt in
      H)
        MOUNTHOME=1
        ;;
      D)
        DAEMON=1
        ;;
      V)
        VERSION=$OPTARG
        ;;
      P)
        PORT=$OPTARG
        ;;
      \?)
        break
        ;;
    esac
done

if [ -z $VERSION ]; then
  AVAILABLE=$(docker image ls --format "{{.Tag}}" zedesk/zdknode)
  VERSION=$(echo $AVAILABLE | cut -d" " -f 1)
fi

# get remaining args
shift $(expr $OPTIND - 1 )

APPNAME=$(basename $PWD)

function EXISTS {
  echo '"'$(docker ps -a --format="{{.Names}}" | grep "^"${APPNAME}"$")'"'
}

echo $VERSION
echo $(EXISTS)

# EXISTS=$(docker ps -a --format="{{.Names}}" | grep ${NAME})

if [[ $PORT ]]; then
   PORTOPT=' -p '${PORT}':8080'
else
   PORTOPT=' -p 8080:8080'
fi

if [ "" == $(EXISTS) ]; then
  echo "create docker"
  DOCKERCMD='docker run '
  OPTION='-v '$PWD':/app '$PORTOPT' --name '$APPNAME
  if [[ $DAEMON ]]; then
    OPTION=' -d '$OPTION
  else
    OPTION=' -it --rm '$OPTION
  fi
  if [[ $MOUNTHOME ]]; then
    OPTION+=' -v '$HOME':/home/web'
  fi

  ${DOCKERCMD} ${OPTION} zedesk/zdknode:${VERSION} $@
else
  if [ $# != 0 ]; then
    DOCKERCMD='docker exec -it '$APPNAME' npm'
    ${DOCKERCMD} $@
  else
    echo "container ${APPNAME} already running : need a command"
    exit 1
  fi
fi
