#!/bin/bash

while getopts ":p:d" opt; do
    case $opt in
       d)
          DAEMON=1
          ;;
       p)
          PORT=$OPTARG
          ;;
    esac
done

# get remaining args
shift $(expr $OPTIND - 1 )

NAME=$(basename $PWD)
CMD='docker run '
EXISTS=$(docker ps -a --format="{{.Names}}" | grep ${NAME})

if [ ! -z $EXISTS ]; then
    if [ $# != 0 ]; then
        if [ $1 == 'stop' ]; then
            docker rm -fv $NAME
            exit 0
        fi
        DOCKERCMD='docker exec -it '$NAME' npm'
        ${DOCKERCMD} $@
	exit 0
    else
        echo "already running, need a npm command"
        exit 1
    fi
fi

if [[ $DAEMON ]]; then
  CMD+=' -d -v '$PWD':/app --name '$NAME
else
  CMD+=' -it --rm -v '$PWD':/app --name '$NAME
fi

if [[ $PORT ]]; then
   CMD+=' -p '${PORT}':8080'
else
   CMD+=' -p 8080'
fi

${CMD} zdknode $@

